package modelo;
// Generated 09-jul-2020 12:30:16 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Areas generated by hbm2java
 */
public class Areas  implements java.io.Serializable {


     private int idA;
     private String area;
     private Set habitacioneses = new HashSet(0);

    public Areas() {
    }

	
    public Areas(int idA, String area) {
        this.idA = idA;
        this.area = area;
    }
    public Areas(int idA, String area, Set habitacioneses) {
       this.idA = idA;
       this.area = area;
       this.habitacioneses = habitacioneses;
    }
   
    public int getIdA() {
        return this.idA;
    }
    
    public void setIdA(int idA) {
        this.idA = idA;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public Set getHabitacioneses() {
        return this.habitacioneses;
    }
    
    public void setHabitacioneses(Set habitacioneses) {
        this.habitacioneses = habitacioneses;
    }




}


