package modelo;
// Generated 09-jul-2020 12:30:16 by Hibernate Tools 4.3.1



/**
 * DispositivosId generated by hbm2java
 */
public class DispositivosId  implements java.io.Serializable {


     private int idD;
     private int idH;
     private int idA;

    public DispositivosId() {
    }

    public DispositivosId(int idD, int idH, int idA) {
       this.idD = idD;
       this.idH = idH;
       this.idA = idA;
    }
   
    public int getIdD() {
        return this.idD;
    }
    
    public void setIdD(int idD) {
        this.idD = idD;
    }
    public int getIdH() {
        return this.idH;
    }
    
    public void setIdH(int idH) {
        this.idH = idH;
    }
    public int getIdA() {
        return this.idA;
    }
    
    public void setIdA(int idA) {
        this.idA = idA;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DispositivosId) ) return false;
		 DispositivosId castOther = ( DispositivosId ) other; 
         
		 return (this.getIdD()==castOther.getIdD())
 && (this.getIdH()==castOther.getIdH())
 && (this.getIdA()==castOther.getIdA());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdD();
         result = 37 * result + this.getIdH();
         result = 37 * result + this.getIdA();
         return result;
   }   


}


