package modelo;
// Generated 09-jul-2020 12:30:16 by Hibernate Tools 4.3.1



/**
 * HabitacionesId generated by hbm2java
 */
public class HabitacionesId  implements java.io.Serializable {


     private int idH;
     private int idA;

    public HabitacionesId() {
    }

    public HabitacionesId(int idH, int idA) {
       this.idH = idH;
       this.idA = idA;
    }
   
    public int getIdH() {
        return this.idH;
    }
    
    public void setIdH(int idH) {
        this.idH = idH;
    }
    public int getIdA() {
        return this.idA;
    }
    
    public void setIdA(int idA) {
        this.idA = idA;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HabitacionesId) ) return false;
		 HabitacionesId castOther = ( HabitacionesId ) other; 
         
		 return (this.getIdH()==castOther.getIdH())
 && (this.getIdA()==castOther.getIdA());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdH();
         result = 37 * result + this.getIdA();
         return result;
   }   


}


