package modelo;
// Generated 09-jul-2020 12:30:16 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private int idU;
     private String nombre;
     private String contra;
     private String tipo;

    public Usuarios() {
    }

    public Usuarios(int idU, String nombre, String contra, String tipo) {
       this.idU = idU;
       this.nombre = nombre;
       this.contra = contra;
       this.tipo = tipo;
    }
   
    public int getIdU() {
        return this.idU;
    }
    
    public void setIdU(int idU) {
        this.idU = idU;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getContra() {
        return this.contra;
    }
    
    public void setContra(String contra) {
        this.contra = contra;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


